apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: k8sapi
spec:
  ports:
  - port: 6443
    targetPort: 6443
  selector:
    app: nginx
  type: LoadBalancer
