apiVersion: v1
kind: Service
metadata:
  name: k8sapi
  labels:
    component: apiserver
    provider: kubernetes
  annotations:
    metallb.universe.tf/address-pool: k8sapi
spec:
  ports:
  - port: 6443
    targetPort: 6443
  type: LoadBalancer
